name: Deploy to GCR

on:
  push:
    tags:
      - 'gcr-v*'

jobs:
  Release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Get tag version
      id: branch_name
      run: |
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

    - name: Deploying docker image to GCR
      uses: RaccoonDev/push-docker-gcr@v1
      with:
        gcr_host: gcr.io
        image_name: django-app
        image_tag: ${{ steps.branch_name.outputs.SOURCE_TAG }}
      env:
        GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
        GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
